global:
  scrape_interval: 5s
remote_write:
  - url: "http://adapter:1234/write"
remote_read:
  - url: "http://adapter:1234/read"
    required_matchers:
      "remote_read": "true"
    read_recent: true
  
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']
  - job_name: monetdb_adapter
    static_configs:
    - targets: ['adapter:8080']
