{
 "title": "Prometheus MonetDB Adapter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Rows Inserted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "monetdb_adapter_rows_inserted_total"
    }
   ]
  },
  {
   "title": "Up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{remote_read=\"true\", job=\"monetdb_adapter\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[30s])",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Rows Read",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "monetdb_adapter_rows_read_total"
    }
   ]
  },
  {
   "title": "50th Percentile Response Sizes (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(monetdb_adapter_http_read_response_size_bytes_bucket{remote_read=\"true\"}[5m])) by (le))",
     "legendFormat": "read"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(monetdb_adapter_http_write_response_size_bytes_bucket{remote_read=\"true\"}[5m])) by (le))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "HTTP Requests/s (by Code)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(monetdb_adapter_http_requests_total{remote_read=\"true\"}[1m])",
     "legendFormat": "{{ method }} - {{ code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests /s (by Handler)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(monetdb_adapter_http_request_duration_seconds_count{remote_read=\"true\"}[1m])",
     "legendFormat": "{{ method }} - {{ handler }}"
    }
   ]
  },
  {
   "title": "50th Percentile HTTP Response Time (Histogram)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(monetdb_adapter_http_request_duration_seconds_bucket{remote_read=\"true\"}[5m])) by (le, handler))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "50th Percentile HTTP Response Time (Actual)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "monetdb_adapter_http_request_duration_seconds_sum{remote_read=\"true\"} / monetdb_adapter_http_request_duration_seconds_count{remote_read=\"true\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Rows Inserted (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(monetdb_adapter_rows_inserted_total{remote_read=\"true\"}[1m])"
    }
   ]
  },
  {
   "title": "Rows Read (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(monetdb_adapter_rows_read_total{remote_read=\"true\"}[1m])"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(monetdb_adapter_queries_total{remote_read=\"true\"}[30s])"
    }
   ]
  },
  {
   "title": "Query Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(monetdb_adapter_query_errors_total{remote_read=\"true\"}[30s])",
     "legendFormat": "Query Errors"
    },
    {
     "expr": "rate(monetdb_adapter_row_errors_total{remote_read=\"true\"}[30s])",
     "legendFormat": "Row Errors"
    },
    {
     "expr": "rate(monetdb_adapter_rowscan_errors_total{remote_read=\"true\"}[30s])",
     "legendFormat": "Row Scan Errors"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "monetdb_adapter_writes_inflight{remote_read=\"true\"}",
     "legendFormat": "writes"
    },
    {
     "expr": "monetdb_adapter_reads_inflight{remote_read=\"true\"}",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "Tables Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "monetdb_adapter_tables_created_total"
    }
   ]
  }
 ]
}